name: test
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
      - name: Run test
        run: go test -v ./...